insert into worker_roles(name, sort_order) values
('Armaturçu / söküb-yığma ustası', 1),
('Kuzov ustası / dəmirçi', 2),
('Rəngsaz', 3),
('Boya hazırlıq ustası', 4),
('PDR ustası', 5),
('Plastik ustası', 6),
('Qaynaqçı', 7),
('Mexanik', 8),
('Avtoelektrik-diaqnost', 9),
('Tuning / retrofit ustası', 10),
('Detailing ustası', 11),
('Cilalama ustası', 12),
('PPF / vinil ustası', 13),
('Şüşə ustası', 14),
('Təkər və disk ustası', 15),
('Kondisioner ustası', 16),
('Universal usta', 17),
('Usta köməkçisi', 18),
('Keyfiyyətə nəzarət üzrə məsul şəxs', 19)
on conflict do nothing;

insert into work_catalog(code, category, name, sort_order) values
('INITIAL_INSPECTION', 'Qəbul və ilkin yoxlama', 'İlkin baxış və defektasiya', 1),
('PHOTO_INTAKE', 'Qəbul və ilkin yoxlama', 'Foto-fiksasiya / qəbul vəziyyətinin qeydə alınması', 2),
('DIAGNOSTICS', 'Qəbul və ilkin yoxlama', 'Kompyuter diaqnostikası', 3),
('FRONT_BUMPER', 'Sökülmə və quraşdırma', 'Ön bamperin sökülməsi/quraşdırılması', 4),
('BODYKIT', 'Sökülmə və quraşdırma', 'Body-kit və tuning detallarının yığılması/quraşdırılması', 5),
('DENT_REPAIR', 'Kuzov və dəmirçi işləri', 'Əzik və deformasiya düzəltmə', 6),
('WELDING', 'Kuzov və dəmirçi işləri', 'Qaynaq işi', 7),
('PAINT_PREP', 'Rəngsaz və boya hazırlığı', 'Səthin təmizlənməsi və boya hazırlığı', 8),
('PAINT', 'Rəngsaz və boya hazırlığı', 'Detalın rənglənməsi', 9),
('POLISH', 'Rəngsaz və boya hazırlığı', 'Boya sonrası cilalama', 10),
('PLASTIC_REPAIR', 'Plastik və kompozit bərpa', 'Plastik bamper təmiri', 11),
('OIL_FILTER', 'Mexaniki işlər', 'Yağ və filtr dəyişimi', 12),
('ELECTRIC_DIAGNOSTICS', 'Elektrik və elektronika', 'Avtoelektrik diaqnostikası', 13),
('PDC', 'Elektrik və elektronika', 'PDC park sensoru quraşdırılması və təmiri', 14),
('HEADLIGHT', 'Şüşə və optika', 'Faranın cilalanması / bərpası', 15),
('M_STYLE', 'Tuning və retrofit', 'M-style / G80-style kuzov çevrilməsi', 16),
('CARPLAY', 'Tuning və retrofit', 'Multimedia / CarPlay retrofit', 17),
('CERAMIC', 'Detailing və qoruyucu işlər', 'Keramik qoruyucu örtük', 18),
('PPF', 'Detailing və qoruyucu işlər', 'PPF qoruyucu plyonka', 19),
('WHEEL_ALIGN', 'Təkər və disk', 'Razval-sxojdeniye / təkər bucaqlarının sazlanması', 20),
('QUALITY', 'Yekun nəzarət və təhvil', 'Yekun texniki yoxlama', 21)
on conflict do nothing;

insert into part_catalog(category, name, sort_order) values
('Kuzov və eksteryer', 'Ön bamper', 1),
('Kuzov və eksteryer', 'Arxa bamper', 2),
('Kuzov və eksteryer', 'Radiator barmaqlığı/böyrək', 3),
('Kuzov və eksteryer', 'Ön lip/splitter', 4),
('Kuzov və eksteryer', 'Arxa diffuser', 5),
('Kuzov və eksteryer', 'Yan ətək/side skirt', 6),
('Kuzov və eksteryer', 'Kapot', 7),
('Kuzov və eksteryer', 'Yan güzgü', 8),
('Kuzov və eksteryer', 'Klips/bərkidici', 9),
('İşıq və optika', 'Ön fara', 10),
('İşıq və optika', 'Arxa fənər/stop', 11),
('İşıq və optika', 'Fara modulu', 12),
('Ön panel, soyutma və kondisioner', 'Radiator paneli/televizor', 13),
('Ön panel, soyutma və kondisioner', 'Mühərrik radiatoru', 14),
('Ön panel, soyutma və kondisioner', 'İnterkuler', 15),
('Mayelər və sərf materialları', 'Mühərrik yağı', 16),
('Mayelər və sərf materialları', 'Antifriz', 17),
('Mayelər və sərf materialları', 'Boya', 18),
('Mayelər və sərf materialları', 'Lak', 19),
('Mayelər və sərf materialları', 'Astar/primer', 20),
('Detailing materialları', 'PPF plyonka', 21),
('Detailing materialları', 'Keramik örtük', 22),
('Detailing materialları', 'Polish pastası', 23),
('Tuning və styling', 'Body-kit komplekti', 24),
('Tuning və styling', 'M paket/M-style detalı', 25)
on conflict do nothing;
