insert into worker_roles(name, sort_order) values
('Armaturçu / söküb-yığma ustası', 1),
('Kuzov ustası / dəmirçi', 2),
('Rəngsaz', 3),
('Boya hazırlıq ustası', 4),
('PDR ustası', 5),
('Plastik ustası', 6),
('Qaynaqçı', 7),
('Mexanik', 8),
('Avtoelektrik-diaqnost', 9),
('Tuning / retrofit ustası', 10),
('Detailing ustası', 11),
('Cilalama ustası', 12),
('PPF / vinil ustası', 13),
('Şüşə ustası', 14),
('Təkər və disk ustası', 15),
('Kondisioner ustası', 16),
('Universal usta', 17),
('Usta köməkçisi', 18),
('Keyfiyyətə nəzarət üzrə məsul şəxs', 19)
on conflict do nothing;

insert into work_catalog(code, category, name, sort_order) values
('INITIAL_INSPECTION', 'Qəbul və ilkin yoxlama', 'İlkin baxış və defektasiya', 1),
('PHOTO_INTAKE', 'Qəbul və ilkin yoxlama', 'Foto-fiksasiya / qəbul vəziyyətinin qeydə alınması', 2),
('DIAGNOSTICS', 'Qəbul və ilkin yoxlama', 'Kompyuter diaqnostikası', 3),
('FRONT_BUMPER', 'Sökülmə və quraşdırma', 'Ön bamperin sökülməsi/quraşdırılması', 4),
('BODYKIT', 'Sökülmə və quraşdırma', 'Body-kit və tuning detallarının yığılması/quraşdırılması', 5),
('DENT_REPAIR', 'Kuzov və dəmirçi işləri', 'Əzik və deformasiya düzəltmə', 6),
('WELDING', 'Kuzov və dəmirçi işləri', 'Qaynaq işi', 7),
('PAINT_PREP', 'Rəngsaz və boya hazırlığı', 'Səthin təmizlənməsi və boya hazırlığı', 8),
('PAINT', 'Rəngsaz və boya hazırlığı', 'Detalın rənglənməsi', 9),
('POLISH', 'Rəngsaz və boya hazırlığı', 'Boya sonrası cilalama', 10),
('PLASTIC_REPAIR', 'Plastik və kompozit bərpa', 'Plastik bamper təmiri', 11),
('OIL_FILTER', 'Mexaniki işlər', 'Yağ və filtr dəyişimi', 12),
('ELECTRIC_DIAGNOSTICS', 'Elektrik və elektronika', 'Avtoelektrik diaqnostikası', 13),
('PDC', 'Elektrik və elektronika', 'PDC park sensoru quraşdırılması və təmiri', 14),
('HEADLIGHT', 'Şüşə və optika', 'Faranın cilalanması / bərpası', 15),
('M_STYLE', 'Tuning və retrofit', 'M-style / G80-style kuzov çevrilməsi', 16),
('CARPLAY', 'Tuning və retrofit', 'Multimedia / CarPlay retrofit', 17),
('CERAMIC', 'Detailing və qoruyucu işlər', 'Keramik qoruyucu örtük', 18),
('PPF', 'Detailing və qoruyucu işlər', 'PPF qoruyucu plyonka', 19),
('WHEEL_ALIGN', 'Təkər və disk', 'Razval-sxojdeniye / təkər bucaqlarının sazlanması', 20),
('QUALITY', 'Yekun nəzarət və təhvil', 'Yekun texniki yoxlama', 21)
on conflict do nothing;

insert into part_catalog(category, name, sort_order) values
('Kuzov və eksteryer', 'Ön bamper', 1),
('Kuzov və eksteryer', 'Arxa bamper', 2),
('Kuzov və eksteryer', 'Radiator barmaqlığı/böyrək', 3),
('Kuzov və eksteryer', 'Ön lip/splitter', 4),
('Kuzov və eksteryer', 'Arxa diffuser', 5),
('Kuzov və eksteryer', 'Yan ətək/side skirt', 6),
('Kuzov və eksteryer', 'Kapot', 7),
('Kuzov və eksteryer', 'Yan güzgü', 8),
('Kuzov və eksteryer', 'Klips/bərkidici', 9),
('İşıq və optika', 'Ön fara', 10),
('İşıq və optika', 'Arxa fənər/stop', 11),
('İşıq və optika', 'Fara modulu', 12),
('Ön panel, soyutma və kondisioner', 'Radiator paneli/televizor', 13),
('Ön panel, soyutma və kondisioner', 'Mühərrik radiatoru', 14),
('Ön panel, soyutma və kondisioner', 'İnterkuler', 15),
('Mayelər və sərf materialları', 'Mühərrik yağı', 16),
('Mayelər və sərf materialları', 'Antifriz', 17),
('Mayelər və sərf materialları', 'Boya', 18),
('Mayelər və sərf materialları', 'Lak', 19),
('Mayelər və sərf materialları', 'Astar/primer', 20),
('Detailing materialları', 'PPF plyonka', 21),
('Detailing materialları', 'Keramik örtük', 22),
('Detailing materialları', 'Polish pastası', 23),
('Tuning və styling', 'Body-kit komplekti', 24),
('Tuning və styling', 'M paket/M-style detalı', 25)
on conflict do nothing;

insert into work_catalog(code, category, name, sort_order) values
('ELECTRIC_INITIAL_CHECK', 'Qəbul və ilkin yoxlama', 'Elektrik və elektron sistemlərin ilkin yoxlanması', 22),
('BODY_GEOMETRY_MEASURE', 'Qəbul və ilkin yoxlama', 'Ban/kuzov geometriyasının ölçülməsi', 23),
('TEST_DRIVE', 'Qəbul və ilkin yoxlama', 'Test sürüşü', 24),
('REPAIR_PLAN_SCOPE', 'Qəbul və ilkin yoxlama', 'İş həcminin və təmir planının dəqiqləşdirilməsi', 25),
('REAR_BUMPER_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Arxa bamperin sökülməsi/quraşdırılması', 26),
('LIGHTS_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Fara və arxa fənərlərin sökülməsi/quraşdırılması', 27),
('FRONT_FENDER_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Ön qanadın sökülməsi/quraşdırılması', 28),
('HOOD_REMOVE_INSTALL_ADJUST', 'Sökülmə və quraşdırma', 'Kapotun sökülməsi/quraşdırılması və sazlanması', 29),
('DOOR_REMOVE_INSTALL_ADJUST', 'Sökülmə və quraşdırma', 'Qapının sökülməsi/quraşdırılması və sazlanması', 30),
('TRUNK_REMOVE_INSTALL_ADJUST', 'Sökülmə və quraşdırma', 'Baqaj qapağının sökülməsi/quraşdırılması və sazlanması', 31),
('SIDE_MIRROR_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Yan güzgünün sökülməsi/quraşdırılması', 32),
('RADIATOR_PANEL_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Radiator paneli / ön panel elementlərinin sökülməsi/quraşdırılması', 33),
('INTERIOR_TRIM_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Salon üzlükləri və dekor elementlərinin sökülməsi/quraşdırılması', 34),
('SEAT_CONSOLE_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Oturacaq, konsol və salon detallarının sökülməsi/quraşdırılması', 35),
('UNDERTRAY_REMOVE_INSTALL', 'Sökülmə və quraşdırma', 'Alt qoruyucu və plastik örtüklərin sökülməsi/quraşdırılması', 36),
('SPOTTER_REPAIR', 'Kuzov və dəmirçi işləri', 'Spotter ilə düzəltmə', 37),
('BODY_PANEL_RESTORE', 'Kuzov və dəmirçi işləri', 'Kuzov panelinin bərpası', 38),
('BODY_PANEL_REPLACE', 'Kuzov və dəmirçi işləri', 'Kuzov panelinin dəyişdirilməsi', 39),
('METAL_SECTION_REPLACE', 'Kuzov və dəmirçi işləri', 'Kəsim və metal hissənin dəyişdirilməsi', 40),
('LONGERON_RESTORE', 'Kuzov və dəmirçi işləri', 'Lonjeron / daşıyıcı elementin bərpası', 41),
('SILL_RESTORE', 'Kuzov və dəmirçi işləri', 'Porog / yan eşik bərpası', 42),
('WHEEL_ARCH_RESTORE', 'Kuzov və dəmirçi işləri', 'Təkər arkasının bərpası', 43),
('PANEL_GAP_ADJUST', 'Kuzov və dəmirçi işləri', 'Qapı, qanad, kapot və baqaj boşluqlarının sazlanması', 44),
('BODY_GEOMETRY_STAND', 'Kuzov və dəmirçi işləri', 'Kuzov geometriyasının stenddə bərpası', 45),
('PDR_PAINTLESS', 'Kuzov və dəmirçi işləri', 'PDR — boyasız əzik düzəltmə', 46),
('SURFACE_CLEAN_PREP', 'Rəngsaz və boya hazırlığı', 'Səthin təmizlənməsi və boya hazırlığı', 47),
('BODY_FILLER', 'Rəngsaz və boya hazırlığı', 'Şpaklyovka', 48),
('SANDING_LEVELING', 'Rəngsaz və boya hazırlığı', 'Zımpara və səth düzləndirilməsi', 49),
('PRIMER', 'Rəngsaz və boya hazırlığı', 'Astar / primer vurulması', 50),
('LOCAL_PAINT', 'Rəngsaz və boya hazırlığı', 'Lokal rəngləmə', 51),
('BLEND_PAINT', 'Rəngsaz və boya hazırlığı', 'Keçid (blend) rəngləmə', 52),
('CLEAR_COAT', 'Rəngsaz və boya hazırlığı', 'Lak vurulması', 53),
('COLOR_MATCH', 'Rəngsaz və boya hazırlığı', 'Rəng uyğunlaşdırılması / boya kodunun seçilməsi', 54),
('PLASTIC_WELD', 'Plastik və kompozit bərpa', 'Plastik qaynaq', 55),
('BROKEN_PLASTIC_RESTORE', 'Plastik və kompozit bərpa', 'Çat və qırıq plastik elementin bərpası', 56),
('FIBERGLASS_RESTORE', 'Plastik və kompozit bərpa', 'Fiberglas / kompozit detal bərpası', 57),
('PLASTIC_SHAPE_RESTORE', 'Plastik və kompozit bərpa', 'Plastik detalın forma bərpası', 58),
('SUSPENSION_REPAIR', 'Mexaniki işlər', 'Asqı sisteminin təmiri', 59),
('STEERING_REPAIR', 'Mexaniki işlər', 'Sükan sisteminin təmiri', 60),
('BRAKE_REPAIR', 'Mexaniki işlər', 'Əyləc sisteminin təmiri', 61),
('COOLING_REPAIR', 'Mexaniki işlər', 'Soyutma sisteminin təmiri', 62),
('ENGINE_MOUNT_REPLACE', 'Mexaniki işlər', 'Mühərrik yastıqlarının dəyişdirilməsi', 63),
('BELT_ROLLER_REPLACE', 'Mexaniki işlər', 'Kəmər və roliklərin dəyişdirilməsi', 64),
('FUEL_SYSTEM_REPAIR', 'Mexaniki işlər', 'Yanacaq sisteminin təmiri', 65),
('INTAKE_SYSTEM_REPAIR', 'Mexaniki işlər', 'Hava giriş sisteminin təmiri', 66),
('TURBO_INTERCOOLER_WORK', 'Mexaniki işlər', 'Turbo / interkuler sistemində iş', 67),
('GEARBOX_REMOVE_INSTALL', 'Mexaniki işlər', 'Sürətlər qutusu ilə bağlı sökülmə/quraşdırma', 68),
('DRIVETRAIN_WORK', 'Mexaniki işlər', 'Kardan / yarımox / diferensial ilə bağlı iş', 69),
('EXHAUST_REPAIR_INSTALL', 'Mexaniki işlər', 'Egzoz sisteminin təmiri və quraşdırılması', 70),
('WIRING_CONTACT_RESTORE', 'Elektrik və elektronika', 'Naqil və kontakt bərpası', 71),
('SENSOR_REPLACE_ADJUST', 'Elektrik və elektronika', 'Sensor dəyişimi və sazlanması', 72),
('HEADLIGHT_MODULE_REPLACE', 'Elektrik və elektronika', 'Fara modulu / ballast / LED modul dəyişimi', 73),
('REAR_CAMERA_INSTALL', 'Elektrik və elektronika', 'Arxa kamera / 360 kamera quraşdırılması', 74),
('MULTIMEDIA_INSTALL', 'Elektrik və elektronika', 'Multimedia sisteminin quraşdırılması', 75),
('AMBIENT_LIGHT_INSTALL', 'Elektrik və elektronika', 'Ambient işıq quraşdırılması', 76),
('MODULE_CODING', 'Elektrik və elektronika', 'Elektron blokların kodlanması / proqramlaşdırılması', 77),
('ADAS_CALIBRATION', 'Elektrik və elektronika', 'ADAS/kamera/radar kalibrlənməsi', 78),
('BATTERY_GENERATOR_STARTER', 'Elektrik və elektronika', 'Akkumulyator, generator və starter üzrə iş', 79),
('WINDSHIELD_REPLACE', 'Şüşə və optika', 'Ön şüşənin dəyişdirilməsi', 80),
('SIDE_GLASS_REPLACE', 'Şüşə və optika', 'Yan şüşənin dəyişdirilməsi', 81),
('REAR_GLASS_REPLACE', 'Şüşə və optika', 'Arxa şüşənin dəyişdirilməsi', 82),
('GLASS_CRACK_REPAIR', 'Şüşə və optika', 'Şüşə çatının lokal bərpası', 83),
('HEADLIGHT_HOUSING_RESTORE', 'Şüşə və optika', 'Faranın korpus bərpası', 84),
('BODY_KIT_INSTALL', 'Tuning və retrofit', 'Body-kit quraşdırılması', 85),
('FRONT_LIP_INSTALL', 'Tuning və retrofit', 'Ön lip / splitter quraşdırılması', 86),
('REAR_DIFFUSER_INSTALL', 'Tuning və retrofit', 'Arxa diffuser quraşdırılması', 87),
('SIDE_SKIRT_INSTALL', 'Tuning və retrofit', 'Yan ətəklər / side skirt quraşdırılması', 88),
('SPOILER_INSTALL', 'Tuning və retrofit', 'Spoiler quraşdırılması', 89),
('SPORT_MIRROR_CAPS', 'Tuning və retrofit', 'Sport güzgü qapaqları quraşdırılması', 90),
('SPORT_STEERING_INSTALL', 'Tuning və retrofit', 'Sport sükan quraşdırılması', 91),
('INTERIOR_RETROFIT', 'Tuning və retrofit', 'Salon retrofit işi', 92),
('LIGHT_OPTICS_RETROFIT', 'Tuning və retrofit', 'İşıq və optika retrofit', 93),
('LOWERING_SUSPENSION', 'Tuning və retrofit', 'Asqının alçaldılması / sport yay və coilover quraşdırılması', 94),
('WHEEL_FITMENT', 'Tuning və retrofit', 'Disk və təkər fitment sazlanması', 95),
('EXTERIOR_WASH', 'Detailing və qoruyucu işlər', 'Eksteryer yuma', 96),
('INTERIOR_DEEP_CLEAN', 'Detailing və qoruyucu işlər', 'Salon detallı təmizləmə', 97),
('CHEMICAL_CLEAN', 'Detailing və qoruyucu işlər', 'Kimyəvi təmizləmə', 98),
('ENGINE_BAY_CLEAN', 'Detailing və qoruyucu işlər', 'Mühərrik bölməsinin təmizlənməsi', 99),
('CLAY_BAR', 'Detailing və qoruyucu işlər', 'Gil (clay) ilə səthin təmizlənməsi', 100),
('ONE_STAGE_POLISH', 'Detailing və qoruyucu işlər', '1 mərhələ cilalama', 101),
('TWO_STAGE_POLISH', 'Detailing və qoruyucu işlər', '2 mərhələ cilalama', 102),
('THREE_STAGE_POLISH', 'Detailing və qoruyucu işlər', '3 mərhələ cilalama', 103),
('VINYL_WRAP', 'Detailing və qoruyucu işlər', 'Vinil / rəng dəyişmə plyonkası', 104),
('WINDOW_TINT', 'Detailing və qoruyucu işlər', 'Şüşələrin tonlanması', 105),
('HEADLIGHT_TAILLIGHT_PPF', 'Detailing və qoruyucu işlər', 'Fara və stopların qoruyucu plyonkası', 106),
('LEATHER_CLEAN_PROTECT', 'Detailing və qoruyucu işlər', 'Dəri təmizləmə və qoruma', 107),
('PLASTIC_RUBBER_RESTORE', 'Detailing və qoruyucu işlər', 'Plastik və rezin elementlərin bərpası', 108),
('TIRE_REMOVE_INSTALL', 'Təkər və disk', 'Təkərin sökülməsi/quraşdırılması', 109),
('BALANCE', 'Təkər və disk', 'Balans', 110),
('WHEEL_REPAIR', 'Təkər və disk', 'Disk təmiri', 111),
('WHEEL_PAINT', 'Təkər və disk', 'Disk rənglənməsi', 112),
('TIRE_REPAIR', 'Təkər və disk', 'Təkər təmiri', 113),
('TPMS_SETUP', 'Təkər və disk', 'TPMS sensoru quraşdırılması/sazlanması', 114),
('FINAL_PARTS_CHECK', 'Yekun nəzarət və təhvil', 'Quraşdırılmış detalların yoxlanması', 115),
('PAINT_BODY_QC', 'Yekun nəzarət və təhvil', 'Boya və kuzov keyfiyyətinə nəzarət', 116),
('FINAL_ELECTRONIC_CHECK', 'Yekun nəzarət və təhvil', 'Elektron sistemlərin yekun yoxlanması', 117),
('FINAL_TEST_DRIVE', 'Yekun nəzarət və təhvil', 'Test sürüşü', 118),
('FINAL_WASH_DELIVERY_PREP', 'Yekun nəzarət və təhvil', 'Yekun yuma və təhvil hazırlığı', 119),
('CUSTOMER_DELIVERY', 'Yekun nəzarət və təhvil', 'Müştəriyə təhvil', 120)
on conflict do nothing;

insert into part_catalog(category, name, sort_order) values
('Kuzov və eksteryer', 'Bamper altlığı/gücləndiricisi', 101),
('Kuzov və eksteryer', 'Bamper kronşteyni', 102),
('Kuzov və eksteryer', 'Ön qanad', 103),
('Kuzov və eksteryer', 'Arxa qanad/quarter panel', 104),
('Kuzov və eksteryer', 'Baqaj qapağı', 105),
('Kuzov və eksteryer', 'Qapı', 106),
('Kuzov və eksteryer', 'Qapı dəstəyi', 107),
('Kuzov və eksteryer', 'Güzgü qapağı', 108),
('Kuzov və eksteryer', 'Kuzov moldinqi', 109),
('Kuzov və eksteryer', 'Təkər arka örtüyü/liner', 110),
('Kuzov və eksteryer', 'Alt qoruyucu', 111),
('Kuzov və eksteryer', 'Mühərrik alt qoruyucusu', 112),
('Kuzov və eksteryer', 'Palçıq qoruyucu', 113),
('Kuzov və eksteryer', 'Spoiler', 114),
('Kuzov və eksteryer', 'Kuzov dekor elementi', 115),
('Kuzov və eksteryer', 'Nömrə çərçivəsi', 116),
('İşıq və optika', 'Duman farası', 117),
('İşıq və optika', 'DRL gündüz işığı', 118),
('İşıq və optika', 'Dönmə siqnalı', 119),
('İşıq və optika', 'LED modul', 120),
('İşıq və optika', 'Ballast/idarəetmə bloku', 121),
('İşıq və optika', 'Fara şüşəsi/lens', 122),
('İşıq və optika', 'Reflektor', 123),
('İşıq və optika', 'Nömrə işığı', 124),
('Ön panel, soyutma və kondisioner', 'Ventilyator', 125),
('Ön panel, soyutma və kondisioner', 'Ventilyator çərçivəsi', 126),
('Ön panel, soyutma və kondisioner', 'Su nasosu', 127),
('Ön panel, soyutma və kondisioner', 'Termostat', 128),
('Ön panel, soyutma və kondisioner', 'Genişlənmə çəni', 129),
('Ön panel, soyutma və kondisioner', 'Soyutma şlanqı', 130),
('Ön panel, soyutma və kondisioner', 'Kondisioner kompressoru', 131),
('Ön panel, soyutma və kondisioner', 'Kondisioner borusu', 132),
('Mühərrik və hava/yanacaq sistemi', 'Mühərrik komplekti', 133),
('Mühərrik və hava/yanacaq sistemi', 'Mühərrik yastığı', 134),
('Mühərrik və hava/yanacaq sistemi', 'Hava filtri', 135),
('Mühərrik və hava/yanacaq sistemi', 'Yağ filtri', 136),
('Mühərrik və hava/yanacaq sistemi', 'Yanacaq filtri', 137),
('Mühərrik və hava/yanacaq sistemi', 'Hava borusu/intake', 138),
('Mühərrik və hava/yanacaq sistemi', 'MAF/MAP sensoru', 139),
('Mühərrik və hava/yanacaq sistemi', 'Drossel', 140),
('Mühərrik və hava/yanacaq sistemi', 'Yanacaq nasosu', 141),
('Mühərrik və hava/yanacaq sistemi', 'Forsunka', 142),
('Mühərrik və hava/yanacaq sistemi', 'Şam', 143),
('Mühərrik və hava/yanacaq sistemi', 'Bobin', 144),
('Mühərrik və hava/yanacaq sistemi', 'Generator', 145),
('Mühərrik və hava/yanacaq sistemi', 'Starter', 146),
('Mühərrik və hava/yanacaq sistemi', 'Kəmər', 147),
('Mühərrik və hava/yanacaq sistemi', 'Rolik', 148),
('Mühərrik və hava/yanacaq sistemi', 'Wastegate aktuatoru', 149),
('Sürətlər qutusu və ötürücü', 'Sürətlər qutusu', 150),
('Sürətlər qutusu və ötürücü', 'Debriyaj komplekti', 151),
('Sürətlər qutusu və ötürücü', 'Maxovik', 152),
('Sürətlər qutusu və ötürücü', 'Hidrotransformator', 153),
('Sürətlər qutusu və ötürücü', 'Kardan', 154),
('Sürətlər qutusu və ötürücü', 'Yarımox', 155),
('Sürətlər qutusu və ötürücü', 'ŞRUS', 156),
('Sürətlər qutusu və ötürücü', 'Diferensial', 157),
('Sürətlər qutusu və ötürücü', 'Reduktor dayağı/bushing', 158),
('Sürətlər qutusu və ötürücü', 'Sürətlər qutusu yastığı', 159),
('Asqı və sükan', 'Amortizator', 160),
('Asqı və sükan', 'Yay', 161),
('Asqı və sükan', 'Coilover', 162),
('Asqı və sükan', 'Amortizator dayağı', 163),
('Asqı və sükan', 'Qol/рычаг', 164),
('Asqı və sükan', 'Saylentblok', 165),
('Asqı və sükan', 'Şaravoy', 166),
('Asqı və sükan', 'Stabilizator linki', 167),
('Asqı və sükan', 'Stabilizator rezini', 168),
('Asqı və sükan', 'Stupitsa/hub', 169),
('Asqı və sükan', 'Podşipnik', 170),
('Asqı və sükan', 'Sükan reykası', 171),
('Asqı və sükan', 'Sükan ucluğu', 172),
('Asqı və sükan', 'Sükan dartqısı', 173),
('Asqı və sükan', 'Sükan nasosu', 174),
('Əyləc sistemi', 'Əyləc diski', 175),
('Əyləc sistemi', 'Əyləc bəndi/pad', 176),
('Əyləc sistemi', 'Əyləc supportu/caliper', 177),
('Əyləc sistemi', 'Əyləc şlanqı', 178),
('Əyləc sistemi', 'Əyləc borusu', 179),
('Əyləc sistemi', 'Əyləc baş silindri', 180),
('Əyləc sistemi', 'ABS sensoru', 181),
('Əyləc sistemi', 'Əyləc mayesi', 182),
('Elektrik və elektronika', 'Akkumulyator', 183),
('Elektrik və elektronika', 'ECU/idarəetmə bloku', 184),
('Elektrik və elektronika', 'BCM/FEM/BDC modulu', 185),
('Elektrik və elektronika', 'Sığorta bloku', 186),
('Elektrik və elektronika', 'Naqil dəsti/wiring', 187),
('Elektrik və elektronika', 'PDC sensoru', 188),
('Elektrik və elektronika', 'Arxa kamera', 189),
('Elektrik və elektronika', '360 kamera', 190),
('Elektrik və elektronika', 'Radar sensoru', 191),
('Elektrik və elektronika', 'Park modulu', 192),
('Elektrik və elektronika', 'Multimedia ekranı', 193),
('Elektrik və elektronika', 'Head unit', 194),
('Elektrik və elektronika', 'Səs gücləndiricisi', 195),
('Elektrik və elektronika', 'Dinamik', 196),
('Elektrik və elektronika', 'Ambient işıq modulu', 197),
('Elektrik və elektronika', 'TPMS sensoru', 198),
('Elektrik və elektronika', 'Müxtəlif elektrik sensoru', 199),
('Salon və təhlükəsizlik', 'Airbag', 200),
('Salon və təhlükəsizlik', 'Təhlükəsizlik kəməri', 201),
('Salon və təhlükəsizlik', 'Oturacaq', 202),
('Salon və təhlükəsizlik', 'Oturacaq mexanizmi', 203),
('Salon və təhlükəsizlik', 'Panel/torpedo', 204),
('Salon və təhlükəsizlik', 'Mərkəzi konsol', 205),
('Salon və təhlükəsizlik', 'Qapı üzlüyü', 206),
('Salon və təhlükəsizlik', 'Tavan üzlüyü', 207),
('Salon və təhlükəsizlik', 'Salon dekoru', 208),
('Salon və təhlükəsizlik', 'Döşəmə/carpet', 209),
('Salon və təhlükəsizlik', 'Pedal dəsti', 210),
('Salon və təhlükəsizlik', 'Salon güzgüsü', 211),
('Şüşə və rezinlər', 'Ön şüşə', 212),
('Şüşə və rezinlər', 'Arxa şüşə', 213),
('Şüşə və rezinlər', 'Yan şüşə', 214),
('Şüşə və rezinlər', 'Şüşə rezini/molding', 215),
('Şüşə və rezinlər', 'Şüşə qaldırıcı mexanizm', 216),
('Şüşə və rezinlər', 'Şüşə motoru', 217),
('Şüşə və rezinlər', 'Şüşəsilən', 218),
('Şüşə və rezinlər', 'Şüşəsilən motoru', 219),
('Şüşə və rezinlər', 'Şüşəyuyan nasosu', 220),
('Egzoz sistemi', 'Egzoz kollektoru', 221),
('Egzoz sistemi', 'Katalizator', 222),
('Egzoz sistemi', 'DPF', 223),
('Egzoz sistemi', 'Orta qazan/rezonator', 224),
('Egzoz sistemi', 'Arxa qazan/muffler', 225),
('Egzoz sistemi', 'Egzoz borusu', 226),
('Egzoz sistemi', 'Egzoz ucluğu', 227),
('Egzoz sistemi', 'Lambda sensoru', 228),
('Egzoz sistemi', 'Egzoz asqısı/rezin', 229),
('Disk və təkər', 'Disk', 230),
('Disk və təkər', 'Təkər', 231),
('Disk və təkər', 'Ehtiyat təkər', 232),
('Disk və təkər', 'Disk boltları', 233),
('Disk və təkər', 'Spacer', 234),
('Disk və təkər', 'Hub-centric ring', 235),
('Disk və təkər', 'TPMS ventil', 236),
('Tuning və styling', 'G80-style detalı', 237),
('Tuning və styling', 'Karbon detal', 238),
('Tuning və styling', 'Sport spoiler', 239),
('Tuning və styling', 'Sport diffuser', 240),
('Tuning və styling', 'Sport lip', 241),
('Tuning və styling', 'Sport side skirt', 242),
('Tuning və styling', 'Sport güzgü qapağı', 243),
('Tuning və styling', 'Sport sükan', 244),
('Tuning və styling', 'Paddle shift detalı', 245),
('Tuning və styling', 'Ambient kit', 246),
('Tuning və styling', 'Retrofit kabel/adapter', 247),
('Tuning və styling', 'Coilover/sport yay', 248),
('Detailing materialları', 'Vinil plyonka', 249),
('Detailing materialları', 'Ton plyonkası', 250),
('Detailing materialları', 'Pad/cilalama diski', 251),
('Detailing materialları', 'Şampun', 252),
('Detailing materialları', 'Degreaser', 253),
('Detailing materialları', 'Dəri təmizləyici', 254),
('Detailing materialları', 'Dəri qoruyucu', 255),
('Detailing materialları', 'Plastik qoruyucu', 256),
('Detailing materialları', 'Mikrofiber', 257),
('Detailing materialları', 'Maskalama lenti', 258),
('Mayelər və sərf materialları', 'Sürətlər qutusu yağı', 259),
('Mayelər və sərf materialları', 'Diferensial yağı', 260),
('Mayelər və sərf materialları', 'Əyləc mayesi', 261),
('Mayelər və sərf materialları', 'Sükan mayesi', 262),
('Mayelər və sərf materialları', 'Kondisioner qazı', 263),
('Mayelər və sərf materialları', 'Şüşəyuyan maye', 264),
('Mayelər və sərf materialları', 'Germetik', 265),
('Mayelər və sərf materialları', 'Yapışdırıcı', 266),
('Mayelər və sərf materialları', 'Şpaklyovka', 267),
('Mayelər və sərf materialları', 'Zımpara', 268),
('Mayelər və sərf materialları', 'Bolt/qayka', 269),
('Mayelər və sərf materialları', 'Klips', 270),
('Mayelər və sərf materialları', 'Elektrik konnektoru', 271)
on conflict do nothing;
